/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_conf2_yang_Loader */

#ifndef _Included_org_conf2_yang_Loader
#define _Included_org_conf2_yang_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_conf2_yang_Loader
 * Method:    loadModule
 * Signature: (Lorg/conf2/yang/comm/DriverHandle;Ljava/lang/String;)Lorg/conf2/yang/comm/DriverHandle;
 */
JNIEXPORT jobject JNICALL Java_org_conf2_yang_Loader_loadModule
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
