/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_conf2_restconf_Service */

#ifndef _Included_org_conf2_restconf_Service
#define _Included_org_conf2_restconf_Service
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_conf2_restconf_Service
 * Method:    sendSetDocRoot
 * Signature: (Lorg/conf2/restconf/DriverHandle;Lorg/conf2/restconf/DataSource;)V
 */
JNIEXPORT void JNICALL Java_org_conf2_restconf_Service_sendSetDocRoot
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_conf2_restconf_Service
 * Method:    startNewService
 * Signature: ()Lorg/conf2/restconf/DriverHandle;
 */
JNIEXPORT jobject JNICALL Java_org_conf2_restconf_Service_startNewService
  (JNIEnv *, jobject);

/*
 * Class:     org_conf2_restconf_Service
 * Method:    echoTest
 * Signature: (Lorg/conf2/restconf/DataSource;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_conf2_restconf_Service_echoTest
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
