/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_conf2_yang_Driver */

#ifndef _Included_org_conf2_yang_Driver
#define _Included_org_conf2_yang_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_conf2_yang_Driver
 * Method:    initializeDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_conf2_yang_Driver_initializeDriver
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
